name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate the snake SVG
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            year.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Push generated snake to main
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update contribution snake animation [skip ci]"
          file_pattern: year.svg
